on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

name: Build PDFs

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Extract Version from Tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Extract Version from Commit
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build PDFs
        uses: docker://ghcr.io/swissmanu/pandoc:latest
        env:
          VERSION: ${{ env.VERSION }}
        with:
          args: make

      - name: Add Version to PDF filename
        run: |
          sudo mv out/thesis.pdf out/thesis-${{ env.VERSION }}.pdf

      - name: Add PDF as Snapshot Artifact
        uses: actions/upload-artifact@v2
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          name: snapshot
          path: out/*.pdf
          retention-days: 10

      - name: Add PDF to Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/*.pdf
