on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

name: Build PDFs

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build PDFs
        uses: docker://ghcr.io/swissmanu/pandoc:latest
        with:
          args: make

      # This step runs only on the main branch:
      - uses: actions/upload-artifact@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: snapshot
          path: out/*.pdf

      # Following Steps run only on version tags:
      # - name: Extract Version from Tag
      #   id: get_version
      #   if: ${{ github.ref != 'refs/heads/main' }}
      #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      # - name: Add Version to PDF filename
      #   if: ${{ github.ref != 'refs/heads/main' }}
      #   run: |
      #     mv out/paper.pdf out/paper-${{ steps.get_version.outputs.VERSION }}.pdf
      #     mv out/reports.pdf out/reports-${{ steps.get_version.outputs.VERSION }}.pdf
      - name: Release
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/*.pdf
